# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 4.0.5
_src_path: gh:epics-containers/services-template-helm
cluster_name: pollux
cluster_namespace: ${FED_ID:-$(id -u)}
cluster_type: dls_cluster
description: t03 IOC Instances and Services
git_platform: github.com
github_org: gilesknap
ioc_group: t03
location: t03
logging_url: https://graylog2.diamond.ac.uk/search?rangetype=relative&fields=message%2Csource&width=1489&highlightMessage=&relative=172800&q=pod_name%3A{service_name}*
repo_uri: https://github.com/gilesknap/t03-services
