apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}-ca-gateway
          command:
           - bash
          args:
           - "-c"
           - "/start-ca.sh"
          env:
            - name: EPICS_CA_AUTO_ADDR_LIST
              value: "NO"
            - name: CA_SERVER_PORT
              value: "9064"
          image: {{ .Values.image }}
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 800m
              memory: 1024Mi
            requests:
              cpu: 200m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
          stdin: true
          tty: true
        - name: {{ .Release.Name }}-pva-gateway
          command:
           - bash
          args:
           - "-c"
           - "/start-pva.sh"
          env:
            - name: EPICS_PVA_AUTO_ADDR_LIST
              value: "NO"
            - name: PVA_SERVER_PORT
              value: "9065"
          image: {{ .Values.image }}
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 800m
              memory: 1024Mi
            requests:
              cpu: 200m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
          stdin: true
          tty: true
      hostNetwork: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 1
