apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - command:
           - bash
          args:
           - "-c"
           - "/start.sh"
          env:
            - name: EPICS_CA_AUTO_ADDR_LIST
              value: "NO"
            - name: EPICS_PVA_AUTO_ADDR_LIST
              value: "NO"
            - name: CA_SERVER_PORT
              value: "9064"
            - name: PVA_SERVER_PORT
              value: "9065"
          image: {{ .Values.image }}
          imagePullPolicy: Always
          name: {{ .Release.Name }}
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
          stdin: true
          tty: true
          # volumeMounts:
          #   - mountPath: /config
          #     name: config-volume
      hostNetwork: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 3
      # at present the built in config in the container is adequate
      # volumes:
      #   - configMap:
      #       defaultMode: 420
      #       name: {{ .Release.Name }}-config
      #     name: config-volume