# yaml-language-server: $schema=https://github.com/epics-containers/ec-helm-charts/releases/download/4.1.3/ioc-instance.schema.json

ioc-instance:
  image: ghcr.io/epics-containers/ioc-adsimdetector-runtime:2024.11.1b1

  resources:
    limits:
      cpu: 1.5
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 256Mi
