apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - command:
           - bash
          args:
           - "-c"
           - "python3 /launch_gateway.py --port 9064 --namespace ${MY_POD_NAMESPACE}"
          env:
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: {{ .Values.image }}
          imagePullPolicy: Always
          name: {{ .Release.Name }}
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
          stdin: true
          tty: true
          volumeMounts:
            - mountPath: /config
              name: config-volume
      hostNetwork: false
      restartPolicy: Always
      terminationGracePeriodSeconds: 3
      volumes:
        - configMap:
            defaultMode: 420
            name: {{ .Release.Name }}-config
          name: config-volume